apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fcg-tech-fase-4
type: Opaque
stringData:
  username: CHANGE_ME
  password: CHANGE_ME
  users-username: CHANGE_ME
  users-password: CHANGE_ME
  catalog-username: CHANGE_ME
  catalog-password: CHANGE_ME
  payments-username: CHANGE_ME
  payments-password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fcg-tech-fase-4
type: Opaque
stringData:
  username: CHANGE_ME
  password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: fcg-tech-fase-4
type: Opaque
stringData:
  username: CHANGE_ME
  password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: fcg-tech-fase-4
type: Opaque
stringData:
  password: CHANGE_ME
