apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  username: YWRtaW4= # admin
  password: YWRtaW4xMjM= # admin123
  RABBITMQ_DEFAULT_USER: YWRtaW4= # admin
  RABBITMQ_DEFAULT_PASS: YWRtaW4xMjM= # admin123