apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: fcg-tech-fase-2
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP